# Generated by Django 2.0.6 on 2018-08-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('parent', models.IntegerField(default=0, null=True)),
                ('groupNumber', models.IntegerField(default=0, null=True)),
                ('groupOrder', models.IntegerField(default=0, null=True)),
            ],
            options={
                'ordering': ['groupNumber', 'groupOrder'],
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('studyImage', models.ImageField(null=True, upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('short_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('attendants', models.PositiveIntegerField(default=0)),
                ('price', models.IntegerField(null=True)),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('startTime', models.TimeField(null=True)),
                ('endTime', models.TimeField(null=True)),
                ('day1', models.CharField(blank=True, max_length=200, null=True)),
                ('day2', models.CharField(blank=True, max_length=200, null=True)),
                ('career1', models.TextField(blank=True)),
                ('career2', models.TextField(blank=True)),
                ('contents', models.TextField(blank=True)),
                ('curriculum1', models.TextField(blank=True)),
                ('curriculum2', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo/%Y/%m')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
            ],
        ),
        migrations.CreateModel(
            name='StudyLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
