# Generated by Django 2.0.6 on 2018-07-31 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0002_auto_20180717_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='studycomment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_recomments', to='studygroups.StudyComment'),
        ),
    ]
