# Generated by Django 2.0.6 on 2018-08-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0002_auto_20180810_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
