# Generated by Django 2.0.6 on 2018-07-31 05:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studygroups', '0003_studycomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='attend_users',
            field=models.ManyToManyField(blank=True, related_name='attend_studygroups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='wish_users',
            field=models.ManyToManyField(blank=True, related_name='wish_studygroups', to=settings.AUTH_USER_MODEL),
        ),
    ]
