# Generated by Django 2.0.6 on 2018-07-31 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0004_auto_20180731_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo/%Y/%m')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
                ('studygroup', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='studygroups.StudyGroup')),
            ],
        ),
    ]
