# Generated by Django 2.0.6 on 2018-07-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0005_studyimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='career1',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='career2',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='contents',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='curriculum1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='curriculum2',
            field=models.TextField(blank=True),
        ),
    ]
