# Generated by Django 2.0.6 on 2018-08-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0007_auto_20180731_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studycomment',
            options={'ordering': ['groupNumber', 'groupOrder']},
        ),
        migrations.AddField(
            model_name='studycomment',
            name='groupNumber',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='studycomment',
            name='groupOrder',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studycomment',
            name='parent',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
