# Generated by Django 2.0.6 on 2018-08-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0008_auto_20180809_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
