# Generated by Django 2.0.6 on 2018-08-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0009_studygroup_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
