# Generated by Django 2.0.6 on 2018-08-10 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturelike',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lecturelike',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_likes', to='lectures.Lecture'),
        ),
        migrations.AddField(
            model_name='lectureimages',
            name='lecture',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lectures.Lecture'),
        ),
        migrations.AddField(
            model_name='lecturecomment',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lecturecomment',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_comments', to='lectures.Lecture'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='attend_users',
            field=models.ManyToManyField(blank=True, related_name='attend_lectures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lecture',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lecture',
            name='wish_users',
            field=models.ManyToManyField(blank=True, related_name='wish_lectures', to=settings.AUTH_USER_MODEL),
        ),
    ]
