# Generated by Django 2.0.6 on 2018-07-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='short_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lectureImage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
