# Generated by Django 2.0.6 on 2018-07-02 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_auto_20180702_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to=settings.AUTH_USER_MODEL),
        ),
    ]
