# Generated by Django 2.0.6 on 2018-08-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_lecture_attendants'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
