# Generated by Django 2.0.6 on 2018-08-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_lecture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
