# Generated by Django 2.0.6 on 2018-07-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0005_auto_20180716_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='day1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='day2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='endTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='startDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='startTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecture',
            name='location',
            field=models.CharField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecture',
            name='short_description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
