# Generated by Django 2.0.6 on 2018-07-18 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0006_auto_20180717_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='price',
        ),
    ]
