# Generated by Django 2.0.6 on 2018-07-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0007_remove_lecture_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
