# Generated by Django 2.0.6 on 2018-07-29 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lectures', '0008_lecture_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='attend_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='attend_lectures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lecture',
            name='wish_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='wish_lectures', to=settings.AUTH_USER_MODEL),
        ),
    ]
