# Generated by Django 2.0.6 on 2018-07-31 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0009_auto_20180729_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturecomment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_recomments', to='lectures.LectureComment'),
        ),
    ]
