# Generated by Django 2.0.6 on 2018-07-31 05:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0010_lecturecomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='attend_users',
            field=models.ManyToManyField(blank=True, related_name='attend_lectures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='wish_users',
            field=models.ManyToManyField(blank=True, related_name='wish_lectures', to=settings.AUTH_USER_MODEL),
        ),
    ]
