# Generated by Django 2.0.6 on 2018-08-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0014_auto_20180731_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturecomment',
            options={'ordering': ['groupNumber', 'groupOrder']},
        ),
        migrations.AddField(
            model_name='lecturecomment',
            name='groupNumber',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='lecturecomment',
            name='groupOrder',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lecturecomment',
            name='parent',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
