# Generated by Django 2.0.6 on 2018-08-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0015_auto_20180809_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='attendants',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
