# Generated by Django 2.0.6 on 2018-08-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0016_auto_20180822_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
