# Generated by Django 2.0.6 on 2018-10-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='career',
            field=models.TextField(null=True),
        ),
    ]
