# Generated by Django 2.0.6 on 2018-08-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Name of User'),
        ),
    ]
