# Generated by Django 2.0.6 on 2018-08-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180810_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['isImportant', '-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='isImportant',
            field=models.NullBooleanField(default=False),
        ),
    ]
