# Generated by Django 2.0.6 on 2018-07-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180703_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='post_creator',
            new_name='creator',
        ),
    ]
