# Generated by Django 2.0.6 on 2018-08-23 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180823_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-isImportant', '-created_at']},
        ),
    ]
