# Generated by Django 2.0.6 on 2018-08-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180703_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('qna', 'Q&A'), ('free', '자유게시판'), ('ask', '문의사항')], max_length=80, null=True),
        ),
    ]
