# Generated by Django 2.0.6 on 2018-08-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180807_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['groupNumber', 'groupOrder']},
        ),
        migrations.AddField(
            model_name='postcomment',
            name='groupNumber',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='groupOrder',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='parent',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
