# Generated by Django 2.0.6 on 2018-08-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_view_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-isImportant', '-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='isImportant',
            field=models.NullBooleanField(default=False),
        ),
    ]
