# Generated by Django 2.0.6 on 2018-07-19 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0002_auto_20180717_2041'),
        ('notifications', '0002_auto_20180704_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studygroups.StudyGroup'),
        ),
    ]
