# Generated by Django 2.0.6 on 2018-07-17 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hitcount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bannerImage', models.ImageField(null=True, upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200, null=True)),
                ('short_description', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('attendants', models.PositiveIntegerField(default=0)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
    ]
