# Generated by Django 2.0.6 on 2018-08-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
