# Generated by Django 2.0.6 on 2018-08-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_banner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
